name: Deploy Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.farcetPush }}
    steps:
      - uses: actions/checkout@v4.1.7
        uses: actions/setup-node@v4
        with:
          node-version: 18
        uses: actions/setup-python@v5
        with:
          pyton-version: '3.12'
        run: |
          npm install -g @azure/static-web-apps-cli
          python -m pip install 'pelican[markdown]'
          pelican content/ -t themes/genus
          swa deploy ./output

